### ISSUE TITLE
"clock" and code inside "clock" don't have any kind of highlighting

### ISSUE THREAD

**Issue by Mizab1** [SnaveSutit/language-mcbuild-lang-mc#1]
![image](https://user-images.githubusercontent.com/67660416/135213567-e1fd7713-e83e-4de6-8d83-4782eaef2391.png)
The above image show a normal block of commands.

![image](https://user-images.githubusercontent.com/67660416/135213642-bd97a3fe-1582-42f8-b0d6-473151936877.png)
And the above shows the clock block, as you can see there isn't a syntax highlighting.

![image](https://user-images.githubusercontent.com/67660416/135213785-508f120b-d362-440e-a54e-9bd643ac6afb.png)
Inspection Mode of "clock" block

**Things I already tried:**
1. Changed the theme.
2. Enabled the arc's syntax highlighter

**Comment by Mizab1** [comment]
I have looked through the code, and from the look of things it requires a "space" to be registered, after giving a space before the opening bracket, it did worked as expected
![image](https://user-images.githubusercontent.com/67660416/135216494-04181be1-9464-400b-ba0d-ee89ef891cff.png)

**Comment by SnaveSutit** [comment]
Ah, I must've mistakenly left the space requirement in there after the time argument

**Comment by Mizab1** [comment]
And also same thing happens with the "dir" block. It also requires a space before the bracket

**Comment by SnaveSutit** [comment]
Fixed
