### ISSUE TITLE
Inline Script Block Edge Cases

### ISSUE THREAD

**Issue by SnaveSutit** [SnaveSutit/language-mcbuild-lang-mc#4]
This issue is being used to collect all known edge cases of inline script blocks not being highlighted.

If you find an edge case that isn't listed here, please post a screenshot demonstrating it!

If I've solved an edge case I'll react to it's image with a thumbs up

**Comment by SnaveSutit** [comment]
Function references
![image](https://user-images.githubusercontent.com/28514936/135546858-29989da4-d891-4f99-a585-3dcecaad03f4.png)

**Comment by SnaveSutit** [comment]
Say command (Idk if I'll be able to fix this one, unquoted strings are annoying)
![image](https://user-images.githubusercontent.com/28514936/135546946-9b011a57-8f7e-4627-ae92-a69fe62f87ab.png)

**Comment by IanSSenne** [comment]
tags 
![image](https://user-images.githubusercontent.com/48780301/135569471-1272f38e-85d2-4fe2-8265-94d7573560ce.png)

**Comment by SnaveSutit** [comment]
block tag references inside of multi-line commands
![image](https://user-images.githubusercontent.com/28514936/135926615-766e9f00-4b38-446f-9434-cc3516dd40ad.png)
